[config]
"secrets/default.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKi5mFDoyYSeNmjBZk2pU7BAmA3tUyCxV0Ix7/pWzyq aostanin@gmail.com"]
"secrets/networkmanager/default.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKi5mFDoyYSeNmjBZk2pU7BAmA3tUyCxV0Ix7/pWzyq aostanin@gmail.com"]
"secrets/terranix/default.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKi5mFDoyYSeNmjBZk2pU7BAmA3tUyCxV0Ix7/pWzyq aostanin@gmail.com"]
"secrets/network/default.nix" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKi5mFDoyYSeNmjBZk2pU7BAmA3tUyCxV0Ix7/pWzyq aostanin@gmail.com"]
"secrets/network/tailscale.json" = ["ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBKi5mFDoyYSeNmjBZk2pU7BAmA3tUyCxV0Ix7/pWzyq aostanin@gmail.com"]
