# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/eedb1b30-6eda-43e5-b8a4-2933749452e1";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/EF31-6C12";
    fsType = "vfat";
  };

  # TODO: virtiofs doesn't support suspend/resume
  boot.blacklistedKernelModules = ["virtiofs"];

  # boot.initrd.availableKernelModules = ["virtiofs"];

  # fileSystems."/mnt/home" = {
  #   device = "home";
  #   fsType = "virtiofs";
  # };

  # fileSystems."/mnt/media" = {
  #   device = "media";
  #   fsType = "virtiofs";
  # };

  # fileSystems."/mnt/personal" = {
  #   device = "personal";
  #   fsType = "virtiofs";
  # };

  swapDevices = [
    {device = "/dev/disk/by-uuid/afa2e1cd-8884-4a49-9679-d64a02e98874";}
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
