# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9150-8B94";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  fileSystems."/nix" = {
    device = "rpool/root/nix";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/661153da-8027-413b-90f7-40ec60411e9c";
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
