# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ahci" "xhci_pci" "virtio_pci" "sd_mod" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bec7754a-46c1-4dea-bc69-3e94b5b818cd";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/17D2-7F36";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/ef0ca2b7-21b3-416e-8664-fd2a8afd164e";}
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
