# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/boot1" = {
    device = "/dev/disk/by-uuid/5569-52EB";
    fsType = "vfat";
  };

  fileSystems."/boot2" = {
    device = "/dev/disk/by-uuid/58BC-D2A3";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  fileSystems."/nix" = {
    device = "rpool/root/nix";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/2f2a1fee-86c3-49be-8027-1e3cab28af02";}
    {device = "/dev/disk/by-uuid/39433c7f-93bf-4a57-9dac-82b6d9acf093";}
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
