{
  imports = [
    ./3dprinting.nix
    ./ai.nix
    ./alacritty.nix
    ./android.nix
    ./chromium.nix
    ./common.nix
    ./desktop.nix
    ./desktop-darwin.nix
    ./desktop-linux.nix
    ./electronics.nix
    ./email.nix
    ./firefox.nix
    ./fish.nix
    ./foot.nix
    ./gaming.nix
    ./git.nix
    ./gnupg.nix
    ./gtk.nix
    ./inhibridge.nix
    ./mpd.nix
    ./neovim.nix
    ./obs-studio.nix
    ./polkit.nix
    ./qt.nix
    ./ssh.nix
    ./sway.nix
    ./syncthing.nix
    ./tmux.nix
    ./trayscale.nix
    ./video.nix
    ./vscode.nix
    ./zellij.nix
    ./zsh.nix
  ];
}
