# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: let
  zfsFilesystem = device: {
    inherit device;
    fsType = "zfs";
    options = ["noatime"];
  };
in {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "mpt3sas" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/3E1E-2057";
      fsType = "vfat";
    };
    "/" = zfsFilesystem "tank/root/nixos";
    "/nix" = zfsFilesystem "tank/root/nix";
    "/home" = zfsFilesystem "tank/home";
    "/var/lib/libvirt" = zfsFilesystem "tank/virtualization/libvirt";
    "/var/lib/libvirt/images" = zfsFilesystem "tank/virtualization/libvirt/images";
    "/var/lib/libvirt/images/ssd" = zfsFilesystem "tank/virtualization/libvirt/images/ssd";
    "/storage/appdata/docker" = zfsFilesystem "tank/appdata/docker";
    "/storage/appdata/docker/ssd" = zfsFilesystem "tank/appdata/docker/ssd";
    "/storage/appdata/scripts" = zfsFilesystem "tank/appdata/scripts";
    "/storage/appdata/temp" = zfsFilesystem "tank/appdata/temp";
    "/storage/backup/devices" = zfsFilesystem "tank/backup/devices";
    "/storage/download" = zfsFilesystem "tank/download";
    "/storage/media/adult" = zfsFilesystem "tank/media/adult";
    "/storage/media/audiobooks" = zfsFilesystem "tank/media/audiobooks";
    "/storage/media/books" = zfsFilesystem "tank/media/books";
    "/storage/media/magazines" = zfsFilesystem "tank/media/magazines";
    "/storage/media/manga" = zfsFilesystem "tank/media/manga";
    "/storage/media/music" = zfsFilesystem "tank/media/music";
    "/storage/media/software" = zfsFilesystem "tank/media/software";
    "/storage/media/videos" = zfsFilesystem "tank/media/videos";
    "/storage/personal" = zfsFilesystem "tank/personal";
    "/var/lib/docker" = zfsFilesystem "tank/virtualization/docker";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/7150d268-bc6c-430c-a8f0-eeacf879b9d9";}
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
