# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/boot1" = {
    device = "/dev/disk/by-uuid/3A2B-B155";
    fsType = "vfat";
    options = ["nofail"];
  };

  fileSystems."/boot2" = {
    device = "/dev/disk/by-uuid/3B7B-1CCB";
    fsType = "vfat";
    options = ["nofail"];
  };

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  fileSystems."/nix" = {
    device = "rpool/root/nix";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  fileSystems."/storage/appdata/games/merged" = {
    device = "overlay";
    fsType = "overlay";
    options = [
      (lib.concatStringsSep "," [
        "lowerdir=/storage/appdata/games/tank/data"
        "upperdir=/storage/appdata/games/vmpool/data"
        "workdir=/storage/appdata/games/vmpool/work"
      ])
      "x-systemd.requires=zfs-mount.service"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/e017aee1-551b-4ced-b51d-1ff8c828bf3b";
      options = ["nofail"];
    }
    {
      device = "/dev/disk/by-uuid/ecced8b5-e088-49d9-beeb-6c8f60806de1";
      options = ["nofail"];
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
