{
  imports = [
    ./adguardhome.nix
    ./adguardhome-sync.nix
    ./archivebox.nix
    ./authelia.nix
    ./changedetection.nix
    ./home-assistant.nix
    ./influxdb.nix
    ./invidious.nix
    ./ir-mqtt-bridge.nix
    ./forgejo.nix
    ./frigate.nix
    ./grafana.nix
    ./guacamole.nix
    ./jobcan.nix
    ./matrix.nix
    ./mealie.nix
    ./miniflux.nix
    ./mosquitto.nix
    ./netbootxyz.nix
    ./nginx.nix
    ./openwakeword.nix
    ./piper.nix
    ./redlib.nix
    ./scrutiny.nix
    ./searxng.nix
    ./syncthing.nix
    ./tasmoadmin.nix
    ./whisper.nix
    ./whoami.nix
    ./unifi.nix
    ./uptime-kuma.nix
    ./valetudopng.nix
    ./vaultwarden.nix
    ./zigbee2mqtt.nix
    ./zwift-offline.nix
  ];
}
