{
  imports = [
    ./archivebox.nix
    ./audiobookshelf.nix
    ./authelia.nix
    ./bazarr.nix
    ./calibre-web.nix
    ./changedetection.nix
    ./comfyui.nix
    ./dawarich.nix
    ./forgejo.nix
    ./frigate.nix
    ./grafana.nix
    ./grist.nix
    ./guacamole.nix
    ./hauk.nix
    ./home-assistant.nix
    ./immich.nix
    ./influxdb.nix
    ./invidious.nix
    ./ir-mqtt-bridge.nix
    ./jellyfin.nix
    ./jellyseerr.nix
    ./jobcan.nix
    ./karakeep.nix
    ./komga.nix
    ./librespeed.nix
    ./lidarr.nix
    ./litellm.nix
    ./lnbits.nix
    ./martin.nix
    ./matrix.nix
    ./mealie.nix
    ./meshcentral.nix
    ./miniflux.nix
    ./mosquitto.nix
    ./navidrome.nix
    ./neko.nix
    ./netbootxyz.nix
    ./nextcloud.nix
    ./caddy.nix
    ./nginx.nix
    ./nzbget.nix
    ./ollama.nix
    ./open-webui.nix
    ./openedai-speech.nix
    ./openwakeword.nix
    ./open-meteo.nix
    ./overpass.nix
    ./photon.nix
    ./piper.nix
    ./prowlarr.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./redlib.nix
    ./scrutiny.nix
    ./searxng.nix
    ./sonarr.nix
    ./speaches.nix
    ./stable-diffusion.nix
    ./stalwart.nix
    ./syncthing.nix
    ./tasmoadmin.nix
    ./tdarr.nix
    ./unifi.nix
    ./uptime-kuma.nix
    ./valetudopng.nix
    ./valhalla.nix
    ./vaultwarden.nix
    ./vpn.nix
    ./webtop.nix
    ./whisper.nix
    ./whoami.nix
    ./wyoming-openai.nix
    ./xbvr.nix
    ./zigbee2mqtt.nix
    ./zwift-offline.nix
  ];
}
