{
  imports = [
    ./adguardhome.nix
    ./backup.nix
    ./cloudflared.nix
    ./common.nix
    ./containers
    ./coredns.nix
    ./desktop.nix
    ./forgejo-runner.nix
    ./home-router
    ./home-server.nix
    ./impermanence.nix
    ./ingress.nix
    ./intel-amt.nix
    ./msmtp.nix
    ./networkmanager.nix
    ./nix-ld.nix
    ./nvtop.nix
    ./phoenixd.nix
    ./pikvm.nix
    ./podman.nix
    ./redir.nix
    ./scrutiny-collector.nix
    ./tailscale.nix
    ./traefik.nix
    ./vfio.nix
    ./virtwold.nix
    ./watchdog.nix
    ./zfs.nix
  ];
}
