# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = ["${modulesPath}/installer/scan/not-detected.nix"];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "mpt3sas" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "i2c-dev"];
  boot.extraModulePackages = [];

  fileSystems."/boot1" = {
    device = "/dev/disk/by-uuid/6FE7-AC4D";
    fsType = "vfat";
    options = ["nofail"];
  };

  fileSystems."/boot2" = {
    device = "/dev/disk/by-uuid/5A1C-CB4B";
    fsType = "vfat";
    options = ["nofail"];
  };

  fileSystems."/" = {
    device = "rpool/root/nixos";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  fileSystems."/nix" = {
    device = "rpool/root/nix";
    fsType = "zfs";
    options = ["zfsutil" "noatime" "X-mount.mkdir"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/334764a1-5ff9-4cb2-8a63-132f99c3410d";
      options = ["nofail"];
    }
    {
      device = "/dev/disk/by-uuid/be604aa1-8ae2-4fad-a0b7-3e1bae2259ae";
      options = ["nofail"];
    }
  ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
